// <auto-generated />
using System;
using FiscalZen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiscalZen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FiscalZenDbContext))]
    [Migration("20260828234003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("AccessKey")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)")
                        .HasColumnName("AccessKey");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DiscountAmount");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DocumentType");

                    b.Property<decimal>("FreightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FreightAmount");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("IssueDate");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.Property<decimal>("ProductsAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ProductsAmount");

                    b.Property<int>("Series")
                        .HasColumnType("int")
                        .HasColumnName("Series");

                    b.Property<int>("TaxRegime")
                        .HasColumnType("int")
                        .HasColumnName("TaxRegime");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAmount");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey");

                    b.ToTable("FiscalDocuments", (string)null);

                    b.HasDiscriminator<string>("DocumentType").HasValue("FiscalDocument");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocumentItem", b =>
                {
                    b.Property<Guid>("FiscalDocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FiscalDocumentId");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.Property<string>("Cfop")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Cfop");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("Ncm");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ProductCode");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalAmount");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("FiscalDocumentId", "Number");

                    b.ToTable("FiscalDocumentItems", (string)null);
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.CreditNfe", b =>
                {
                    b.HasBaseType("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument");

                    b.Property<int>("CreditType")
                        .HasColumnType("int")
                        .HasColumnName("CreditType");

                    b.HasDiscriminator().HasValue("NfeCredit");
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.DebitNfe", b =>
                {
                    b.HasBaseType("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument");

                    b.Property<int>("DebitType")
                        .HasColumnType("int")
                        .HasColumnName("DebitType");

                    b.HasDiscriminator().HasValue("NfeDebit");
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.Nfce", b =>
                {
                    b.HasBaseType("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument");

                    b.HasDiscriminator().HasValue("Nfce");
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.NormalNfe", b =>
                {
                    b.HasBaseType("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument");

                    b.HasDiscriminator().HasValue("NfeNormal");
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.ReturnNfe", b =>
                {
                    b.HasBaseType("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument");

                    b.Property<string>("ReferencedAccessKey")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)")
                        .HasColumnName("ReferencedAccessKey");

                    b.HasDiscriminator().HasValue("NfeReturn");
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument", b =>
                {
                    b.OwnsOne("FiscalZen.Domain.FiscalDocuments.ValueObjects.TaxSummary", "Taxes", b1 =>
                        {
                            b1.Property<Guid>("FiscalDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CBS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CBS");

                            b1.Property<decimal>("COFINS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("COFINS");

                            b1.Property<decimal>("IBS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("IBS");

                            b1.Property<decimal>("ICMS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ICMS");

                            b1.Property<decimal>("IPI")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("IPI");

                            b1.Property<decimal>("PIS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PIS");

                            b1.HasKey("FiscalDocumentId");

                            b1.ToTable("FiscalDocuments");

                            b1.WithOwner()
                                .HasForeignKey("FiscalDocumentId");
                        });

                    b.Navigation("Taxes")
                        .IsRequired();
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocumentItem", b =>
                {
                    b.HasOne("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument", null)
                        .WithMany("Items")
                        .HasForeignKey("FiscalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FiscalZen.Domain.FiscalDocuments.ValueObjects.TaxSummary", "Taxes", b1 =>
                        {
                            b1.Property<Guid>("FiscalDocumentItemFiscalDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("FiscalDocumentItemNumber")
                                .HasColumnType("int");

                            b1.Property<decimal>("CBS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CBS");

                            b1.Property<decimal>("COFINS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("COFINS");

                            b1.Property<decimal>("IBS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("IBS");

                            b1.Property<decimal>("ICMS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ICMS");

                            b1.Property<decimal>("IPI")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("IPI");

                            b1.Property<decimal>("PIS")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PIS");

                            b1.HasKey("FiscalDocumentItemFiscalDocumentId", "FiscalDocumentItemNumber");

                            b1.ToTable("FiscalDocumentItems");

                            b1.WithOwner()
                                .HasForeignKey("FiscalDocumentItemFiscalDocumentId", "FiscalDocumentItemNumber");
                        });

                    b.Navigation("Taxes")
                        .IsRequired();
                });

            modelBuilder.Entity("FiscalZen.Domain.FiscalDocuments.Entities.FiscalDocument", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
